package nba;
// Generated 14 dic 2022 9:25:05 by Hibernate Tools 5.6.7.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * EstadisticasId generated by hbm2java
 */
@Entity
public class EstadisticasId implements java.io.Serializable {

	@Id
	private String temporada;
	private int codigoJugador;

	public EstadisticasId() {
	}

	public EstadisticasId(String temporada, int codigoJugador) {
		this.temporada = temporada;
		this.codigoJugador = codigoJugador;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

	public int getCodigoJugador() {
		return this.codigoJugador;
	}

	public void setCodigoJugador(int codigoJugador) {
		this.codigoJugador = codigoJugador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadisticasId))
			return false;
		EstadisticasId castOther = (EstadisticasId) other;

		return ((this.getTemporada() == castOther.getTemporada()) || (this.getTemporada() != null
				&& castOther.getTemporada() != null && this.getTemporada().equals(castOther.getTemporada())))
				&& (this.getCodigoJugador() == castOther.getCodigoJugador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTemporada() == null ? 0 : this.getTemporada().hashCode());
		result = 37 * result + this.getCodigoJugador();
		return result;
	}

}
